name: sanadflow_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- UI & ANIMATION ---
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  lucide_icons: ^0.257.0
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1
  flutter_animate: ^4.5.2

  # --- BACKEND & NETWORK ---
  supabase_flutter: ^2.12.0
  cached_network_image: ^3.4.1
  http: ^1.1.0
  connectivity_plus: ^7.0.0
  
  # --- VIDEO PLAYER (INI YANG TADI HILANG) ---
  video_player: ^2.10.1
  chewie: ^1.13.0
  
  # --- UTILITIES ---
  url_launcher: ^6.3.2      # Buat WA & Link Sosmed
  share_plus: ^12.0.1       # Buat Share
  path_provider: ^2.1.5
  package_info_plus: ^9.0.0
  intl: ^0.20.2
  
  # --- AUTH ---
  google_sign_in: ^6.2.1
  image_picker: ^1.2.1
  file_picker: ^10.3.10
  youtube_player_iframe: ^5.2.2
  webview_flutter: ^4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # --- ASSETS ---
  assets:
    - assets/images/